* DONE Задокументировать sway
=Sway - это i3 совместимый плиточный wayland композитор.= 
** Настройка
Sway настроить очень просто, т.к. синтаксис интуитивно понятен.
Начнём с простого:
*** Cоздание переменных
Для создание переменной нужно, =ввести параметр set, названиe
					   и что она делает.=
~set $term foot~ - создать переменную для терминала.
Так можно делать почти для всего: клавиш, цветов, программ итд.

*** Привязка клавиш
Вообще есть три способа привязать клавишу:
=bindsym - хоткей привязанный к раскладке.=
=bindcode - хоткей не привязанный к раскладке.=
=bindswitch - хоткей для ноутбука в режиме планшета.=

~bindsym Mod1+f exec firefox~ - на нажатие Alt и f
			         появится firefox.
~bindsym --to-code Mod1+f exec firefox~ - на нажатие Alt и f
	      вне зависимости от раскладки появится firefox.
	      
P.S. Еще можно писать конструкцию для нескольких хоткеев через {}.
~bindsym --to-code {
Mod1+f exec firefox ...}~

*** Автостарт
Здесь всё очень просто =exec и команда.=
~exec $term~ - будет вызывать переменную term
		       при старте при старте.

*** Bar
Bar в sway настраивается с помощью переменной bar.
bar * {...} (мне он не нужен, так что я не добавлял её)

*** Border
Рамки обычно делаеются по вкусу, я покажу свою конфигурацию:
~titlebar_padding 1~ её размер
~font pango:Any_font_name 0.01~ - размер шрифта (на 0 выставить нельзя)
~titlebar_border_thickness 0~ - толщина заголовка
~client.focused   $green $green $green $green $green~ - цвета рамки окна на котором мы находимся
~client.unfocused $grey $grey $grey $grey $grey~ - цвета всех остальных
P.S переменные цветов нужно создавать самому
